variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - analyze
  - test
  - package
  - test_deployment
  - productive_deployment
  - notification

.android_docker_image:
  image: xetics/flutter:1.5.4-stable
  tags:
    - flutter-android

    - bundle install
test:
  extends: .android_docker_image
  stage: test
  script:
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 5 days

build_android:
  stage: package
  extends: .android_key_store
  script: flutter build apk --release --build-number=$CI_PIPELINE_ID
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
    expire_in: 1 day

analyze.sonarqube:
  stage: analyze
  image: sonarsource/sonar-scanner-cli:latest
  allow_failure: false
  script:
    - sonar-scanner
    - Dsonar.host.url=https://www.cs.technik.fhnw.ch/sonarqube
    - Dsonar.language=flutter
    - Dsonar.sources=lib
    - Dsonar.tests=test
    - Dsonar.login=$CI_SONARQUBE_TOKEN
    - Dsonar.projectKey=BetterGardensv2
    - Dsonar.projectName=BetterGardensv2
