variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - test
  - analyze
  - package
  - test_deployment
  - productive_deployment
  - notification

.android_docker_image:
  image: cirrusci/flutter:latest

test:
  extends: .android_docker_image
  stage: test
  before_script:
    - flutter pub get
    - flutter clean
    - flutter --version
    - flutter pub global activate junitreport
    - pub global activate dart_code_metrics
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - flutter build
    - flutter test --machine | tojunit -o report.xml
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    when: always
    paths:
      - coverage
    reports:
      junit:
        - report.xml

analyze.sonarqube:
  stage: analyze
  image: ichlaffterlalu/sonar-scanner-flutter-cli:latest
  allow_failure: false
  script:
    - sonar-scanner -Dsonar.host.url=https://www.cs.technik.fhnw.ch/sonarqube -Dsonar.language=flutter -Dsonar.sources=lib -Dsonar.tests=test -Dsonar.login=$CI_SONARQUBE_TOKEN -Dsonar.projectKey=BetterGardensv2 -Dsonar.projectName=BetterGardensv2