variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - test
  - analyze
  - package
  - test_deployment
  - productive_deployment
  - notification

.android_docker_image:
  image: cirrusci/flutter:latest

analyze.sonarqube:
  stage: analyze
  image: ichlaffterlalu/sonar-scanner-flutter-cli:latest
  allow_failure: false
  script:
    - flutter upgrade
    - flutter pub get
    - flutter test
    - flutter test --machine > tests.output
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
    - sonar-scanner -Dsonar.host.url=https://www.cs.technik.fhnw.ch/sonarqube -Dsonar.language=flutter -Dsonar.sources=lib -Dsonar.tests=test -Dsonar.login=$CI_SONARQUBE_TOKEN -Dsonar.projectKey=BetterGardensv2 -Dsonar.projectName=BetterGardensv2
